### ISSUE TITLE
`stormpath setup` fails

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-cli#32]
Installation was successful via pip, but the `stormpath setup` command fails with this output:
```
Traceback (most recent call last):
  File "/usr/local/bin/stormpath", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: six>=1.6.1
```

This is on OSX 10.3.9 and Python 2.7.5

**Comment by lhazlewood** [comment]
Can we close this out?  

Given its simplicity, it seems that our official stance on Mac should be "If you don't have Python installed on your Mac, do so with homebrew": 

`brew install python`

Then install the Stormpath CLI:

`pip install stormpath`

**Comment by rdegges** [comment]
Yes -- we can close this now. Thanks @lhazlewood Users should 100% install using homebrew. If anything, we should update our docs to be more clear on this.
